version: '3'
services:
    todo-app:
        build:
            dockerfile: ./Dockerfile
            context: .
        container_name: ${TODO_CONTAINER_NAME}
        ports:
            - ${PORT}:3000
        volumes: 
            - ${VOLUME_PATH_ENV}:/opt/app/.env
        networks:
            - todoNetwork
        restart: always
        depends_on:
            - postgres
    postgres:
        image: postgres
        container_name: ${DB_CONTAINER_NAME}
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - dbData:/var/lib/postgresql/data
        networks:
            - todoNetwork
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}

volumes:
  dbData:

networks:
    todoNetwork:
        driver: bridge